### ISSUE TITLE
Send intent form Java application

### ISSUE THREAD

**Issue by antoninkriz** [PaulFreund/SteelHRAutomate#4]
Hello,
I am trying to broadcast the "android.intent.action.STEELHR" intent from an app I am making right now, but for some reason, nothing happens. I am using this code:

    Intent intent = new Intent();
    intent.setAction("android.intent.action.STEELHR");
    intent.setData(Uri.parse("Hello world"));
    sendBroadcast(intent);

Can you please help me? Thank you

**Comment by PaulFreund** [comment]
I have not yet created an app that sends intents. Maybe you can try to compare your sent intent to the one that my Automate script produces and see if there are any differences.
